# action.yml
name: 'Flutter test & build'
description: 'Test and build a Flutter project.'
inputs:
  channel:
    description: 'Flutter channel'
    required: true
    default: 'stable'
outputs:
  ls:
    description: 'Result of ls'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.channel }}
